[build]
  command = "cd ta-solution-frontend && npm install && npm run build"
  publish = "ta-solution-frontend/dist"

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
